/*
 * April 2nd, 2020
 * Erika Graham
 * Math Methods
 */

/**
 *
 * @author kikag
 */
public class FrmMathMethods extends javax.swing.JFrame {

    /**
     * Creates new form FrmMathMethods
     */
    public FrmMathMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblMaxIns = new javax.swing.JLabel();
        txtMax1 = new javax.swing.JTextField();
        txtMax2 = new javax.swing.JTextField();
        btnMax = new javax.swing.JButton();
        lblMaxAns = new javax.swing.JLabel();
        lblMinAns = new javax.swing.JLabel();
        btnMin = new javax.swing.JButton();
        lblMinIns = new javax.swing.JLabel();
        txtMin2 = new javax.swing.JTextField();
        txtMin1 = new javax.swing.JTextField();
        lblPOWAns = new javax.swing.JLabel();
        btnPOW = new javax.swing.JButton();
        lblPOWIns = new javax.swing.JLabel();
        txtPOW1 = new javax.swing.JTextField();
        txtPOW2 = new javax.swing.JTextField();
        lblHypoAns = new javax.swing.JLabel();
        lblHypoIns = new javax.swing.JLabel();
        btnHypotenuse = new javax.swing.JButton();
        txtHypo2 = new javax.swing.JTextField();
        txtHypo1 = new javax.swing.JTextField();
        lblFloorIns = new javax.swing.JLabel();
        lblFloorAns = new javax.swing.JLabel();
        btnFloor = new javax.swing.JButton();
        txtFloor = new javax.swing.JTextField();
        lblCeilAns = new javax.swing.JLabel();
        lblCeilIns = new javax.swing.JLabel();
        btnCeil = new javax.swing.JButton();
        txtCeil = new javax.swing.JTextField();
        lblSqrtIns = new javax.swing.JLabel();
        txtSqrt = new javax.swing.JTextField();
        btnSqrt = new javax.swing.JButton();
        lblSqrtAns = new javax.swing.JLabel();
        lblRadAns = new javax.swing.JLabel();
        btnRadians = new javax.swing.JButton();
        lblRadIns = new javax.swing.JLabel();
        txtRad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 153));
        lblTitle.setText("MAGICAL MATH METHODS");

        lblMaxIns.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblMaxIns.setText("Enter two numbers and click the button. The program will display the largest of the two.");

        btnMax.setText("Largest");
        btnMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxActionPerformed(evt);
            }
        });

        lblMaxAns.setText("...");

        lblMinAns.setText("...");

        btnMin.setText("Smallest");
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });

        lblMinIns.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblMinIns.setText("Enter two numbers and click the button. The program will display the smallest of the two.");

        txtMin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMin1ActionPerformed(evt);
            }
        });

        lblPOWAns.setText("...");

        btnPOW.setText("To The Power Of...");
        btnPOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPOWActionPerformed(evt);
            }
        });

        lblPOWIns.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblPOWIns.setText("Enter two numbers and click the button. The program will display the first number to the power of the second.");

        lblHypoAns.setText("...");

        lblHypoIns.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblHypoIns.setText("Enter the lenght of two sides of a right angle triangle. The program will display the hypotenuse of the triangle.");

        btnHypotenuse.setText("Hypotenuse");
        btnHypotenuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHypotenuseActionPerformed(evt);
            }
        });

        lblFloorIns.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblFloorIns.setText("Enter a decimal value. The program will display the value rounded down to the nearest integer.");

        lblFloorAns.setText("...");

        btnFloor.setText("Rounded Down");
        btnFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFloorActionPerformed(evt);
            }
        });

        lblCeilAns.setText("...");

        lblCeilIns.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblCeilIns.setText("Enter a decimal value. The program will display the value rounded up to the nearest integer.");

        btnCeil.setText("Rounded Up");
        btnCeil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeilActionPerformed(evt);
            }
        });

        lblSqrtIns.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblSqrtIns.setText("Enter an integer. The program will display the square root of the integer.");

        btnSqrt.setText("Square Root");
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });

        lblSqrtAns.setText("...");

        lblRadAns.setText("...");

        btnRadians.setText("In Radians");
        btnRadians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadiansActionPerformed(evt);
            }
        });

        lblRadIns.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblRadIns.setText("Enter an angle in degrees. The program will display the angle in radians.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(txtFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnFloor)
                        .addGap(61, 61, 61)
                        .addComponent(lblFloorAns))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(txtMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txtMax2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(btnMax)
                        .addGap(54, 54, 54)
                        .addComponent(lblMaxAns))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(txtMin1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(txtMin2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnMin)
                        .addGap(72, 72, 72)
                        .addComponent(lblMinAns))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtPOW1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(txtPOW2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnPOW)
                        .addGap(37, 37, 37)
                        .addComponent(lblPOWAns))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(txtHypo1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(txtHypo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnHypotenuse)
                        .addGap(74, 74, 74)
                        .addComponent(lblHypoAns))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(lblTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(txtRad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnRadians)
                        .addGap(74, 74, 74)
                        .addComponent(lblRadAns))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSqrtIns)
                            .addComponent(lblCeilIns))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(68, 68, 68)
                                    .addComponent(txtCeil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(69, 69, 69)
                                    .addComponent(btnCeil)
                                    .addGap(7, 7, 7))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(71, 71, 71)
                                    .addComponent(txtSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSqrt)
                                    .addGap(24, 24, 24)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(lblCeilAns))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(lblSqrtAns)))))
                    .addComponent(lblFloorIns)
                    .addComponent(lblMaxIns)
                    .addComponent(lblMinIns)
                    .addComponent(lblPOWIns)
                    .addComponent(lblHypoIns)
                    .addComponent(lblRadIns))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblMaxIns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMax1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMax2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMax)
                    .addComponent(lblMaxAns))
                .addGap(18, 18, 18)
                .addComponent(lblMinIns, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMin)
                    .addComponent(lblMinAns))
                .addGap(18, 18, 18)
                .addComponent(lblPOWIns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPOW1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPOW2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPOW)
                    .addComponent(lblPOWAns))
                .addGap(18, 18, 18)
                .addComponent(lblHypoIns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHypo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHypo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHypotenuse)
                    .addComponent(lblHypoAns))
                .addGap(18, 18, 18)
                .addComponent(lblFloorIns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFloor)
                    .addComponent(lblFloorAns))
                .addGap(18, 18, 18)
                .addComponent(lblCeilIns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCeil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCeil)
                    .addComponent(lblCeilAns))
                .addGap(18, 18, 18)
                .addComponent(lblSqrtIns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSqrtAns)
                    .addComponent(btnSqrt))
                .addGap(18, 18, 18)
                .addComponent(lblRadIns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRadians)
                    .addComponent(lblRadAns))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        // get the values from the user
        int Min1 = Integer.parseInt(txtMin1.getText());
        int Min2 = Integer.parseInt(txtMin2.getText());
        // perform the operation using a Math method
        int Smallest = Math.min(Min2, Min1);
        // print the result to the user
        lblMinAns.setText(String.valueOf(Smallest));
    }//GEN-LAST:event_btnMinActionPerformed

    private void btnMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxActionPerformed
        // get the values from the user
        int Max1 = Integer.parseInt(txtMax1.getText());
        int Max2 = Integer.parseInt(txtMax2.getText());
        // perform the operation using a Math method
        int Largest = Math.max(Max1, Max2);
        // print the result to the user
        lblMaxAns.setText(String.valueOf(Largest));
    }//GEN-LAST:event_btnMaxActionPerformed

    private void btnPOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPOWActionPerformed
        // get the values from the user
        int Num = Integer.parseInt(txtPOW1.getText());
        int Power = Integer.parseInt(txtPOW2.getText());
        // perform the operation using a Math method
        double Result = Math.pow(Num, Power);
        // print the result to the user
        lblPOWAns.setText(String.valueOf(Result));
    }//GEN-LAST:event_btnPOWActionPerformed

    private void btnHypotenuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHypotenuseActionPerformed
        // get the values from the user
        double Num1 = Double.parseDouble(txtHypo1.getText());
        double Num2 = Double.parseDouble(txtHypo2.getText());
        // perform the operation using a Math method
        double Hypotenuse = Math.hypot(Num1, Num2);
        // print the result to the user
        lblHypoAns.setText(String.valueOf(Hypotenuse));
    }//GEN-LAST:event_btnHypotenuseActionPerformed

    private void btnFloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloorActionPerformed
        // get the value from the user
        double RoDown = Double.parseDouble(txtFloor.getText());
        // print the answer to the operation 
        lblFloorAns.setText(String.valueOf(Math.floor(RoDown)));
    }//GEN-LAST:event_btnFloorActionPerformed

    private void btnCeilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeilActionPerformed
        // get the value from the user
        double RoUp = Double.parseDouble(txtCeil.getText());
        // print the answer to the operation 
        lblCeilAns.setText(String.valueOf(Math.ceil(RoUp)));
    }//GEN-LAST:event_btnCeilActionPerformed

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
        // get the value from the user
        int Root2 = Integer.parseInt(txtSqrt.getText());
        // print the answer to the operation 
        lblSqrtAns.setText(String.valueOf(Math.sqrt(Root2)));
    }//GEN-LAST:event_btnSqrtActionPerformed

    private void btnRadiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadiansActionPerformed
        // get the value from the user
        double Rad = Double.parseDouble(txtRad.getText());
        // print the answer to the operation 
        lblRadAns.setText(String.valueOf(Math.toRadians(Rad)));
    }//GEN-LAST:event_btnRadiansActionPerformed

    private void txtMin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMathMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCeil;
    private javax.swing.JButton btnFloor;
    private javax.swing.JButton btnHypotenuse;
    private javax.swing.JButton btnMax;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnPOW;
    private javax.swing.JButton btnRadians;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCeilAns;
    private javax.swing.JLabel lblCeilIns;
    private javax.swing.JLabel lblFloorAns;
    private javax.swing.JLabel lblFloorIns;
    private javax.swing.JLabel lblHypoAns;
    private javax.swing.JLabel lblHypoIns;
    private javax.swing.JLabel lblMaxAns;
    private javax.swing.JLabel lblMaxIns;
    private javax.swing.JLabel lblMinAns;
    private javax.swing.JLabel lblMinIns;
    private javax.swing.JLabel lblPOWAns;
    private javax.swing.JLabel lblPOWIns;
    private javax.swing.JLabel lblRadAns;
    private javax.swing.JLabel lblRadIns;
    private javax.swing.JLabel lblSqrtAns;
    private javax.swing.JLabel lblSqrtIns;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCeil;
    private javax.swing.JTextField txtFloor;
    private javax.swing.JTextField txtHypo1;
    private javax.swing.JTextField txtHypo2;
    private javax.swing.JTextField txtMax1;
    private javax.swing.JTextField txtMax2;
    private javax.swing.JTextField txtMin1;
    private javax.swing.JTextField txtMin2;
    private javax.swing.JTextField txtPOW1;
    private javax.swing.JTextField txtPOW2;
    private javax.swing.JTextField txtRad;
    private javax.swing.JTextField txtSqrt;
    // End of variables declaration//GEN-END:variables
}
